# Generated by Django 5.0.1 on 2024-02-03 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainName', models.CharField(max_length=100)),
                ('TrainNo', models.IntegerField()),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('DepartureTime', models.CharField(max_length=100)),
                ('ArivalTime', models.CharField(max_length=100)),
                ('Distance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Add_route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route', models.CharField(max_length=100)),
                ('Distance', models.IntegerField()),
                ('Fare', models.IntegerField()),
                ('Train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.addtrain')),
            ],
        ),
    ]
