# Generated by Django 5.0.1 on 2024-02-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addtrain_add_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('Cpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Add_route',
        ),
    ]
