# Generated by Django 5.0.1 on 2024-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_contact_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('TrainName', models.CharField(max_length=100)),
                ('TrainNo', models.IntegerField()),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('DepartureTime', models.CharField(max_length=100)),
                ('Distance', models.CharField(max_length=100)),
            ],
        ),
    ]
